# Generated by Django 4.0.5 on 2022-07-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A_Customer',
            fields=[
                ('customerid', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(default='Anish', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=500)),
                ('contact', models.IntegerField(default=1111111111)),
                ('building', models.CharField(default='untitled', max_length=100)),
                ('street', models.CharField(default='untitled', max_length=200)),
                ('landmark', models.CharField(default='untitled', max_length=200)),
                ('city', models.CharField(default='untitled', max_length=50)),
                ('state', models.CharField(default='untitled', max_length=50)),
                ('pincode', models.IntegerField(default='0')),
                ('wallet', models.FloatField(default='0', max_length=50)),
                ('rewards', models.FloatField(default='50')),
            ],
        ),
    ]
