# Generated by Django 4.0.5 on 2022-07-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Product',
        ),
    ]
