# Generated by Django 4.0.5 on 2022-07-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_product_date_product_description_product_disc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='image/default/Unknown.jpeg', upload_to='image/product'),
        ),
    ]
